version: '3'

services: 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
      
  adminer:
    image: adminer
    ports:
      - 8180:8080
    networks:
      - node-network
      
  app:
    build: 
      context: node
    container_name: app
    command: node server.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db
  nginx:
    build:
      context: .
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network        
     

networks: 
  node-network:
    driver: bridge      
